tarea1/urls.py
from django.contrib import admin
from django.urls import path
from aplicacion import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),
    path('products/', views.products, name="products"),
    path('form/', views.form,name="form"),
    path('register/',views.userForm,name='register'),
    path('addproduct/',views.productForm,name='addproduct'),
    path('signin/',views.signin, name='signin'),
    path('productdetail/<int:product_id>/',views.productDetail,name='productdetail'),
    path('addtocart/<int:product_id>/', views.addToCart, name='addtocart'),
    path('view_cart/', views.viewCart, name='viewcart'),
    path('logout/', views.signout, name='logout'),
    path('checkout/', views.checkout, name='checkout')
    
    
]

aplicacion/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    platform = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    image = models.TextField(blank=True)
    
    def __str__(self):
        return self.name + ' ' + self.platform
    
    
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product,through='ItemCart')
    
    def __str__(self):
        return f'Cart de {self.user.first_name}'
    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    order_number = models.CharField(max_length=20,default=0, unique=False)
    total_price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'Order {self.order_number} for {self.user.username}'
    
class ItemCart(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE,default=1)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return f'{self.quantity} x {self.product.name} en {self.cart}'
    





    

aplicacion/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Product


class UserForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password1 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name','platform','description','price','quantity','image']

aplicacion/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db import IntegrityError
from django.utils import timezone
from django.http import JsonResponse
from .forms import UserForm,ProductForm
from .models import Cart,Product,ItemCart,Order
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib import messages

def index(request):
    return render(request,'products/index.html')

def products(request):
    products = Product.objects.all()

    return render(request,'products/products.html',{
        'products':products
    })
    
def productDetail(request,product_id):
    if request.method == 'GET':
        product = get_object_or_404(Product,pk=product_id)
        return render(request,'products/productdetail.html',{
            'product':product
        })

def form(request):
    if request.method == 'POST':

        name = request.POST.get('name')
        email = request.POST.get('emailAddress')
        message = request.POST.get('message')

        subject = 'Nuevo mensaje de contacto'
        message_content = f'Nombre: {name}\nCorreo Electrónico: {email}\nMensaje: {message}'

        send_mail(
            subject,
            message_content,
            'jaimesilvalorca@gmail.com', 
            ['jaimesilvalorca@gmail.com'],
            fail_silently=False,
        )
        return render(request, 'user/contacto.html',{
            'message':'Mensaje enviado correctamente'
        })

    return render(request, 'user/contacto.html')

def userForm(request):
    if request.method == 'GET':
        return render(request,'user/register.html',{
            'form':UserForm,
        })
    else:
        user = UserForm(request.POST)
        new_user = user.save(commit=False)
        new_user.save()
        login(request,new_user)
        nuevo_carrito = Cart.objects.create(user=new_user)
        return redirect('products')

def addToCart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)

    item_cart, item_created = ItemCart.objects.get_or_create(product=product, cart=cart)
    
    if not item_created:
        item_cart.quantity += 1
        item_cart.save()
    
    return redirect('products')

def viewCart(request):
    cart = Cart.objects.get(user=request.user)
    items = ItemCart.objects.filter(cart=cart)

    products_info = []
    total_price = 0

    for item in items:
        product_info = {
            'name': item.product.name,
            'price': item.product.price,
            'quantity_in_cart': item.quantity,
        }
        product_info['total'] = product_info['price'] * product_info['quantity_in_cart']
        total_price += product_info['total']
        products_info.append(product_info)

    return render(request, 'cart/view_cart.html', {'cart': cart, 'products_info': products_info, 'total_price': total_price})
    

def productForm(request):
    if request.method == 'GET':
        return render(request,'administrator/product.html',{
            'form':ProductForm
        })
    else:
        product = ProductForm(request.POST)
        new_product = product.save(commit=False)
        new_product.save()
        return render(request,'administrator/product.html',{
            'form':ProductForm,
            'message':'Producto agregado correctamente'
        })
    
def signin(request):
    if request.method == 'GET':
        return render(request,'user/signin.html',{
            'form':AuthenticationForm
        })
    else:
        user = authenticate(request,
                            username=request.POST['username'],
                            password=request.POST['password']
                            )
        if user is None:
            return render(request,'user/signin.html',{
                'form':AuthenticationForm,
                'error':'Username or password is incorrect'
            })
        else:
            login(request,user)
            return (redirect('products'))
        
def signout(request):
    logout(request)
    return redirect('index')

def checkout(request):
   
    cart = Cart.objects.get(user=request.user)
    order_number = timezone.now().strftime('%Y%m%d%H%M%S')
    order = Order.objects.create(user=request.user, order_number=order_number, total_price=0)
    products_in_cart = cart.products.all()
    total_price = 0
    for product_in_cart in products_in_cart:
        ItemCart.objects.create(product=product_in_cart, cart=cart, order=order, quantity=product_in_cart.quantity)
        total_price += product_in_cart.price * product_in_cart.quantity

    order.total_price = total_price
    order.save()
    send_order_email(order)
    cart.products.clear()

    return render(request, 'order/checkout_success.html', {'order': order})

def send_order_email(order):
    subject = f'Confirmación de pedido #{order.order_number}'
    html_message = render_to_string('order/order_confirmation_email.html', {'order': order})
    plain_message = strip_tags(html_message)
    from_email = 'jaimesilvalorca@gmail.com'
    to_email = [order.user.email]

    send_mail(subject, plain_message, from_email, to_email, html_message=html_message)

aplicacion/templates/administrator/product.html
{% extends "layouts/layout.html"%}

{% block contenido-principal %}

<style>
    .container {
        max-width: 400px;
        margin: 50 auto;
        padding: 20px;
        background-color: #fff;
        border: 1px solid #e2e2e2;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    
    h1 {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
        text-align: center;
    }
    
    form {
        text-align: left;
    }
    
    label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }
    
    input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 10px;
        box-sizing: border-box;
    }
    
    .helptext {
        font-size: 14px;
        color: #666;
    }
    
    button {
        display: block;
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        color: #fff;
        text-align: center;
        font-weight: bold;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    
    button:hover {
        background-color: #0056b3;
    }
</style>

    <div class="container">
        <h1>Formulario para agregar producto</h1>
        <center>{{message}}</center>
        <form action="/addproduct/" method="POST">
            {% csrf_token %}            
            <label for="id_name">Name:</label>
            <input type="text" name="name" maxlength="100" required id="id_name">
            
            <label for="id_platform">Platform:</label>
            <input type="text" name="platform" maxlength="50" required id="id_platform">
            
            <label for="id_description">Description:</label>
            <textarea name="description" cols="45" rows="5" id="id_description"></textarea>
            
            <label for="id_price">Price:</label>
            <input type="number" name="price" min="0" required id="id_price">
            
            <label for="id_quantity">Quantity:</label>
            <input type="number" name="quantity" min="0" required id="id_quantity">
            
            <label for="id_image">Image:</label>
            <textarea name="image" cols="45" rows="5" id="id_image"></textarea>
            
            <button type="submit">Enviar</button>
        </form>
    </div>

{% endblock contenido-principal %}

aplicacion/templates/cart/view_cart.html
<!-- templates/cart/view_cart.html -->
{% extends "layouts/layout.html" %}

{% block contenido-principal %}

<h1 style="text-align: center;">Carrito de Compras</h1>

{% if products_info %}
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Producto</th>
          <th>Precio</th>
          <th>Cantidad</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for product_info in products_info %}
          <tr>
            <td>{{ product_info.name }}</td>
            <td>{{ product_info.price }}</td>
            <td>{{ product_info.quantity_in_cart }}</td>
            <td>{{ product_info.total }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p>Total: {{ total_price }}</p>
    <p>Cantidad de productos en el carrito: {{ cart.products.count }}</p>

    <form method="POST" action="{% url "checkout" %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Finalizar Pedido</button>
    </form>
  </div>
{% else %}
  <p>Su carrito está vacío.</p>
{% endif %}

{% endblock contenido-principal %}

aplicacion/templates/layouts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0d6044bda3.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>      
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        main {
            flex: 1;
        }
    </style>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-primary bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="{% url 'index' %}">Ecommerce Inacap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active text-white" aria-current="page" href="{% url 'index' %}">Home</a>
                    <a class="nav-link text-white" href="{% url 'products' %}">Productos</a>
                    <a class="nav-link text-white" href="{% url 'form' %}">Contacto</a>
                    {% if user.is_authenticated and user.is_staff %}    
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="productDropdown" role="button"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Administrar
                        </a>
                        <div class="dropdown-menu" aria-labelledby="productDropdown">
                            <a class="nav-link disabled" aria-disabled="true"><center>Productos</center></a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url "addproduct" %}">Agregar Producto</a>
                            <a class="dropdown-item" href="#">Eliminar Producto</a>
                            <a class="dropdown-item" href="#">Modificar Producto</a>
                            <a class="nav-link disabled" aria-disabled="true"><center>Usuarios</center></a>
                            <a class="dropdown-item" href="#">Eliminar Producto</a>
                            <a class="dropdown-item" href="#">Modificar Producto</a>
                            <div class="dropdown-divider"></div>
                        </div>

                        {% endif %}
                    </div>
                
                </div>
            </div>
            <a href="{% url "viewcart" %}"><i class="fas fa-shopping-cart text-white"></i></a> 
            
            <div class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <div class="nav-item dropdown">
                        
                        <a class="nav-link dropdown-toggle text-white" href="#" id="userDropdown" role="button"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        
                        <div class="dropdown-menu" aria-labelledby="userDropdown">
                            
                            <a class="dropdown-item" href="#">Perfil</a>

                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url "logout" %}">Cerrar Sesión</a>
                        </div>
                    </div>
                {% else %}
                    <a class="nav-link text-white" href="{% url "signin" %}">Iniciar Sesión</a>
                    <a class="nav-link text-white" href="{% url "register" %}">Crear Cuenta</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- Contenido principal -->
    <main>
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    {% block contenido-principal %}
                    {% endblock contenido-principal %}
                </div>
            </div>
        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-primary text-white text-center p-3">
        <p>Todos los derechos reservados &copy; 2023</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</body>

</html>

aplicacion/templates/order/checkout_success.html
{% extends "layouts/layout.html" %}

{% block contenido-principal %}

<h1 style="text-align: center;">Pedido Confirmado</h1>

<div class="container">
    <p>¡Gracias por tu pedido! Aquí están los detalles:</p>
    
    <h3>Detalles del Pedido:</h3>
    <p>Número de Pedido: {{ order.order_number }}</p>
    <p>Total: {{ order.total_price }}</p>
    
    <h3>Productos:</h3>
    <ul>
        {% for item in order.items.all %}
            <li>{{ item.product.name }} - Cantidad: {{ item.quantity }}</li>
        {% endfor %}
    </ul>

    <p>Recibirás un correo de confirmación con más detalles. ¡Esperamos que disfrutes tus productos!</p>
</div>

{% endblock contenido-principal %}

aplicacion/templates/order/order_confirmation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmación de Pedido</title>
</head>
<body>
    <h2>Confirmación de Pedido</h2>
    <p>Gracias por tu pedido. Aquí están los detalles:</p>
    
    <h3>Detalles del Pedido:</h3>
    <p>Número de Pedido: {{ order.order_number }}</p>
    <p>Total: {{ order.total_price }}</p>
    
    <h3>Productos:</h3>
    <ul>
        {% for item in order.items.all %}
            <li>{{ item.product.name }} - Cantidad: {{ item.quantity }}</li>
        {% endfor %}
    </ul>

    <p>Gracias por elegirnos.</p>
</body>
</html>

aplicacion/templates/products/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenido al Ecommerce JS</title>
    <style>
        body {
            background-color: #007BFF;
            color: #ffffff;
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0;
            padding: 0;
        }

        h1 {
            font-size: 36px;
            margin: 20px 0;
        }

        .button-container {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-top: 20px;
        }

        .button {
            background-color: #ffffff;
            color: #007BFF;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            font-size: 18px;
            cursor: pointer;
            text-decoration: none;
            transition: background-color 0.3s ease;
        }

        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Bienvenido al Ecommerce JS</h1>
    <div class="button-container">
        <a class="button" href="{% url "register" %}">Crear Cuenta</a>
        <a class="button" href="{% url "signin" %}">Iniciar Sesión</a>
    </div>
</body>
</html>

aplicacion/templates/products/productdetail.html
{% extends "layouts/layout.html" %}

{% block contenido-principal %}

<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
    p {
        font-weight: 500;
    }

    .card {
        width: 18rem;
        border: 1px solid #ccc;
        border-radius: 8px;
        overflow: hidden;
        transition: box-shadow 0.3s ease-in-out;
    }

    .card:hover {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card img {
        width: 100%; /* Cambiado a 100% para ocupar el ancho completo de la tarjeta */
        height: auto;
    }

    .card-body {
        padding: 16px;
    }

    .card-title {
        font-size: 1.25rem;
        margin-bottom: 8px;
    }

    .card-text {
        font-size: 1rem;
        color: #555;
        margin-bottom: 12px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

    .btn-link {
        color: #007bff;
        text-decoration: none;
        cursor: pointer;
    }
</style>

<body>
    <h1 style="text-align: center;">Lista de juegos</h1>
    <br>
    <div class="container-fluid d-flex align-items-center justify-content-center">
        <div class="row">
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{product.image}}" class="card-img-top" alt="{{product.name}}">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">Plataforma: {{ product.platform }}</p>
                        <p class="card-text">Precio: {{ product.price }}</p>
                        <p class="card-text">Stock: {{ product.quantity}}</p>
                        <a href="{% url 'addtocart' product.id %}" class='btn btn-primary' onclick="showAlert()">Agregar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script>
    function showAlert() {
        Swal.fire({
            title: 'Producto agregado al carrito',
            icon: 'success',
            showConfirmButton: false,
            timer: 1500
        });
    }
</script>

{% endblock contenido-principal %}

aplicacion/templates/products/products.html
{% extends "layouts/layout.html"%}

{% block contenido-principal %}

<style>
    p {
        font-weight: 500;
    }

    .card {
        width: 18rem;
        border: 1px solid #ccc;
        border-radius: 8px;
        overflow: hidden;
        transition: box-shadow 0.3s ease-in-out;
    }

    .card:hover {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card img{
        width: 200px;
        height: 300px;
        align-self: center;
    }

    .card-body {
        padding: 16px;
    }

    .card-title {
        font-size: 1.25rem;
        margin-bottom: 8px;
    }

    .card-text {
        font-size: 1rem;
        color: #555;
        margin-bottom: 12px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

    .btn-link {
        color: #007bff;
        text-decoration: none;
        cursor: pointer;
    }
</style>

<body>
    <h1 style="text-align: center;">Lista de juegos</h1>
    <br>
    <div class="container">
        <div class="row">
            {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{product.image}}" class="card-img-top" alt="{{product.name}}">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">Plataforma: {{ product.platform }}</p>
                        <p class="card-text">Precio: {{ product.price }}</p>
                        <p class="card-text">Stock: {{ product.quantity }}</p>
                        <a href="{% url 'addtocart' product.id %}" class='btn btn-primary' onclick="showAlert()">Agregar</a>
                        <a href="/productdetail/{{product.id}}" class='btn btn-link'>Más detalles</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
<script>
    function showAlert() {
        Swal.fire({
            title: 'Producto agregado al carrito',
            icon: 'success',
            showConfirmButton: false,
            timer: 1500
        });
    }
</script>

{% endblock contenido-principal %}

aplicacion/templates/user/contacto.html
{% extends "layouts/layout.html"%}

{% block contenido-principal %}

<style>
    main{
        height: 86vh;
    }
</style>

<main class="form">
  <center>{{message}}</center>
    <div class="container py-4">
      <form id="contactForm" action='/form/' method='POST'>
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="name">Nombre</label>
          <input class="form-control" id="name" name='name' type="text" placeholder="Ingrese su nombre"
            data-sb-validations="required" />
        </div>
        <div class="mb-3">
          <label class="form-label" for="emailAddress">Correo</label>
          <input class="form-control" id="emailAddress" name='emailAddress' type="email" placeholder="Ingrese su correo"
            data-sb-validations="required, email" />
        </div>
        <div class="mb-3">
          <label class="form-label" for="message">Mensaje</label>
          <textarea class="form-control" id="message" name='message' type="text" placeholder="Mensaque que quiere enviar"
            style="height: 10rem;" data-sb-validations="required"></textarea>
        </div>
        <div class="d-grid">
          <button class="btn btn-primary btn-lg enabled" id="submitButton" type="submit">Enviar</button>
        </div>
      </form>
    </div>
  </main>

  {% endblock contenido-principal %}

aplicacion/templates/user/register.html
<style>
    body {
        background-color: #f4f4f4;
        font-family: Arial, sans-serif;
    }

    .container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border: 1px solid #e2e2e2;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    h1 {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
        text-align: center;
    }

    form {
        text-align: left;
    }

    label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    .helptext {
        font-size: 14px;
        color: #666;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        color: #fff;
        text-align: center;
        font-weight: bold;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    button:hover {
        background-color: #0056b3;
    }

    .back-to-login-link {
        font-size: 16px;
        text-align: center;
        display: block;
        margin-top: 10px;
    }
</style>

<div class="container">
    {{error}}
    <h1>Registrar Usuario</h1>
    
    <form action="/register/" method="POST">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        <input type="text" name="username" maxlength="150" autofocus required id="id_username">

        <label for="id_first_name">First name:</label>
        <input type="text" name="first_name" maxlength="150" id="id_first_name">

        <label for="id_last_name">Last name:</label>
        <input type="text" name="last_name" maxlength="150" id="id_last_name">

        <label for="id_email">Email:</label>
        <input type="email" name="email" maxlength="320" required id="id_email">

        <label for="id_password1">Contraseña:</label>
        <input type="password" name="password1" required id="id_password1">

        <label for="id_password2">Password confirmation:</label>
        <input type="password" name="password2" autocomplete="new-password" required id="id_password2">

        <button>Enviar</button>
    </form>
</div>

aplicacion/templates/user/signin.html
{% extends "layouts/layout.html"%}

{% block contenido-principal %}

<h1>Sign in </h1>

{{error}}
<form action="/signin/" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>
        signin
    </button>

</form>

{% endblock contenido-principal %}